name: Node Unit Tests
runs:
  using: "composite"
  steps:
    - name: Create Checksum
      run: sh .github/scripts/checksum.sh /tmp/checksums.txt
    - name: Install Root Dependencies
      run: npm install --ignore-scripts
      env:
        NPM_CONFIG_UNSAFE_PERM: true
    - name: Boostrap Dependencies
      run: npx lerna bootstrap --no-ci
    - name: Unit tests
      run: npm run test