name: Node Unit Tests
runs:
  using: "composite"
  steps:
    - name: Create Checksum
      run: sh .github/scripts/checksum.sh /tmp/checksums.txt
      shell: bash
    - name: Print Node Version
      run: echo "$(node --version)"
      shell: bash
    # - name: Install Dependencies
    #   run: |
    #     npm install --ignore-scripts
    #     npx lerna bootstrap --no-ci
    #   env:
    #     NPM_CONFIG_UNSAFE_PERM: true
    #   shell: bash
    # - name: Unit tests
    #   run: npm run test
    #   shell: bash